# Site settings
title: VA GitHub Handbook
description: A collection of guides and policies to help you with your work.
email:
permalink: pretty
author:
  name: GitHub Team at the VA
  email: some.email@va.gov
canonical_domain: department-of-veterans-affairs.github.io
url: https://department-of-veterans-affairs.github.io
baseurl: /github-handbook

slack:
  organization: lighthouseva
  channel: github-project-team

github:
  organization: department-of-veterans-affairs
  repository: github-handbook
  default_branch: master

exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

collections:
  pages:
    output: true
    permalink: /:path/

# Google Analytics tracking code for handbook
google_analytics_ua:
safe: true
navigation:
- text: Welcome to the VA
  blurb: |
    <div>
      <p>Welcome to GitHub, a powerful platform for individuals and organizations to discover, share, and contribute to code — and to manage software (and other) projects.</p>
      <p>The VA uses GitHub to enable collaboration and transparency around project artifacts in a way that is secure and compliant.</p>
    </div> 
  url: welcome-to-VA/
  internal: true
  generated: true
  children:    
  - text: Getting Started with GitHub 🚀
    blurb: |
      Here are some topics to get you started with GitHub. Feel free to explore more of our documentation at <a href="https://help.github.com">help.github.com</a>
    children:
    - text: Learn to use GitHub
      children:
      - text: Sign up for GitHub training
        url: https://vaww.oit.va.gov/services/github/github-training
        internal: false
        new_tab: true
      - text: Learn at your own pace
        url: https://lab.github.com
        internal: false
        new_tab: true
    - text: More in Depth docs
      children:
      - text: GitHub Bootcamp
        url: https://help.github.com/en/categories/bootcamp
        internal: false
        new_tab: true
      - text: Basic Setup
        url: https://help.github.com/en/categories/setup
        internal: false
        new_tab: true
      - text: GitHub Glossary
        url: https://help.github.com/en/articles/github-glossary
        internal: false
        new_tab: true
      - text: Using Git
        url: https://help.github.com/en/categories/using-git
        internal: false
        new_tab: true
      - text: GitHub Desktop
        url: https://desktop.github.com/
        internal: false
        new_tab: true
      - text: GitHub Desktop Help documents 
        url: https://help.github.com/en/desktop
        internal: false
        new_tab: true
  - text: GitHub at the VA 
    blurb: |
      There are some things you should know about how the VA uses GitHub.
    children:
    - text: Get an account if you don't have one
      url: https://github.com/join
      internal: false
      new_tab: true
    - text: Already have an account? Well then, add your VA email address to it
      url: https://github.com/settings/emails
      internal: false
      new_tab: true
    - text: Joining the VA GitHub Organization
      url: join-va-org/
      internal: true
    - text: 2FA Requirements
      url: 2fa-requirements/
      internal: true
    - text: Learn about the two versions of GitHub in use at the VA and request access
      url: https://vaww.oit.va.gov/services/github/
      internal: false
      new_tab: true
  # - text: Additional Infomation
  #   children:
  #   - text: Glossary
  #     url: glossary/
  #     internal: true
  #   - text: Bookmarks
  #     url: bookmarks/
  #     internal: true
    # - text: VA Code of Conduct
    #   url: code-of-conduct/
    #   internal: true
    # - text: Security incidents
    #   url: security-incidents/
    #   internal: true
    # - text: Sensitive information
    #   url: sensitive-information/
    #   internal: true
